/**
 * Type definitions for the OpenCode Autosave Conversation plugin.
 * These types define the internal data structures used for session tracking,
 * message formatting, and plugin configuration.
 */

/**
 * Information about a tracked session.
 * Used to map session IDs to their corresponding markdown files
 * and track parent-child relationships between sessions.
 */
export interface SessionInfo {
  /** Unique session ID from OpenCode */
  id: string;

  /** Parent session ID (undefined for main sessions) */
  parentID?: string;

  /** Session title or extracted topic for filename */
  title: string;

  /** Full filesystem path to this session's markdown file */
  filePath: string;

  /** Timestamp when session was created */
  createdAt: Date;

  /** IDs of child sessions (subagent tasks) */
  childSessionIDs: string[];
}

/**
 * A formatted message ready for markdown output.
 * Contains pre-rendered content suitable for file writing.
 */
export interface FormattedMessage {
  /** Message role - user input or assistant response */
  role: 'user' | 'assistant';

  /** Fully formatted markdown content */
  content: string;

  /** Message creation timestamp */
  timestamp: Date;
}

/**
 * View generation configuration for conversation records.
 */
export interface ViewConfig {
  /** Whether to enable automatic view generation */
  enabled: boolean;

  /** Output formats: 'html' for overview page */
  formats: ('html')[];

  /** Debounce delay for view regeneration (milliseconds) */
  debounceMs: number;
}

/**
 * Plugin configuration options.
 * V1 uses hardcoded defaults; future versions may expose these.
 */
export interface PluginConfig {
  /** Directory to save conversations (relative to project root) */
  saveDirectory: string;

  /** Maximum characters for topic portion of filename */
  maxTopicLength: number;

  /** Debounce delay for idle saves (milliseconds) */
  debounceMs: number;

  /** View generation settings */
  view: ViewConfig;
}

/**
 * Markdown 中标记系统注入上下文的引用块首行。
 * formatter 写入、view-generator 解析（synthetic 内容识别）共用，勿单独修改一侧。
 */
export const INJECTED_CONTEXT_MARKER = '> 🪄 *[系统注入上下文 / Injected Context]*';

/**
 * 主会话级真实用户输入的轮次分隔符（HTML 注释，渲染时不可见）。
 * formatter 写入；view-generator 以其作为新轮次边界信号，
 * 轮次编号由解析侧按 block 内分隔符序数现场计算，此处不携带编号。
 */
export const TURN_SEPARATOR = '<!-- AUTORECORD-TURN -->';

/**
 * Default configuration values for V1.
 * These are hardcoded and not user-configurable in this version.
 */
export const DEFAULT_CONFIG: PluginConfig = {
  saveDirectory: './conversations',
  maxTopicLength: 30,
  debounceMs: 2000,
  view: {
    enabled: true,
    formats: ['html'],
    debounceMs: 10000,
  },
};

/**
 * Child session data for inline embedding.
 * Contains the title and messages for a subagent session.
 */
export interface ChildSessionData {
  /** Child session title (agent name or description) */
  title: string;

  /** Child session creation timestamp */
  createdAt: Date;

  /** All messages from the child session */
  messages: MessageData[];
}

/**
 * Token usage accounting for one assistant message.
 * Mirrors the SDK's `AssistantMessage.tokens` with flattened cache fields.
 */
export interface TokenUsageData {
  /** Prompt tokens sent to the model */
  input: number;

  /** Completion tokens generated by the model */
  output: number;

  /** Reasoning/thinking tokens (subset of output for reasoning models) */
  reasoning: number;

  /** KV-cache read hits */
  cacheRead: number;

  /** KV-cache writes */
  cacheWrite: number;
}

/**
 * Aggregated usage statistics for a whole session (main + child sessions).
 */
export interface SessionUsageStats {
  /** Model ID -> aggregated usage row */
  byModel: Record<
    string,
    {
      calls: number;
      input: number;
      output: number;
      reasoning: number;
      cacheRead: number;
      cacheWrite: number;
      cost: number;
    }
  >;

  /** Sum of all assistant message costs (USD) */
  totalCost: number;

  /** Sum of input + output + reasoning tokens (cache excluded) */
  totalTokens: number;

  /** Number of assistant messages counted */
  assistantMessages: number;
}

/**
 * Simplified message data extracted from SDK response.
 * Contains only the fields needed for formatting.
 */
export interface MessageData {
  /** Message ID */
  id: string;

  /** Message role */
  role: 'user' | 'assistant';

  /** Message parts (text, tool calls, files, etc.) */
  parts: PartData[];

  /** Creation timestamp */
  createdAt: number;

  /** Model ID used for this assistant message (e.g. "claude-sonnet-4-5") */
  modelID?: string;

  /** Provider ID used for this assistant message (e.g. "anthropic") */
  providerID?: string;

  /** Cost of this assistant message in USD */
  cost?: number;

  /** Token usage of this assistant message */
  tokens?: TokenUsageData;

  /** Wall-clock duration in ms (time.completed - time.created) */
  durationMs?: number;

  /**
   * Finish reason reported by the provider (e.g. "stop", "max-tokens",
   * "aborted"). Absent when the provider did not report one.
   */
  finishReason?: string;

  /** Structured failure identity, e.g. "APIError: rate limited" */
  errorMessage?: string;

  /** True when this assistant message is a compaction summary */
  summary?: boolean;
}

/**
 * Union type for message parts.
 * Supports text, tool calls, files, and reasoning parts.
 */
export type PartData =
  | TextPartData
  | ToolPartData
  | FilePartData
  | ReasoningPartData
  | OtherPartData;

/**
 * Text content part.
 */
export interface TextPartData {
  type: 'text';
  text: string;
  /**
   * True when this text was injected by the system (context injection)
   * rather than typed by the human user.
   */
  synthetic?: boolean;
}

/**
 * Tool execution part with full input/output details.
 */
export interface ToolPartData {
  type: 'tool';
  tool: string;
  state: {
    status: string;
    input?: Record<string, unknown>;
    output?: string;
    title?: string;
    error?: string;
  };
}

/**
 * File attachment part.
 */
export interface FilePartData {
  type: 'file';
  filename?: string;
  url: string;
  mime: string;
  /** Local path after saving base64 image to disk (relative to md file) */
  localPath?: string;
}

/**
 * Reasoning/thinking part (for reasoning models).
 */
export interface ReasoningPartData {
  type: 'reasoning';
  text: string;
}

/**
 * Catch-all for other part types we don't specifically handle.
 */
export interface OtherPartData {
  type: string;
  [key: string]: unknown;
}
